import ArgumentParser
import ASCPlugin

private nonisolated(unsafe) let plugins = PluginLoader.discover()

@main
struct ASC: AsyncParsableCommand {
    static let configuration = CommandConfiguration(
        commandName: "asc",
        abstract: "App Store Connect CLI",
        version: ascVersion,
        subcommands: [
            AppsCommand.self,
            AppSetupCommand.self,
            InitCommand.self,
            VersionsCommand.self,
            LocalizationsCommand.self,
            VersionLocalizationsCommand.self,
            ScreenshotSetsCommand.self,
            ScreenshotsCommand.self,
            AppInfosCommand.self,
            AppInfoLocalizationsCommand.self,
            BuildsCommand.self,
            SubmitCommand.self,
            ValidateCommand.self,
            ReleaseCommand.self,
            PublishCommand.self,
            PricingCommand.self,
            TestFlightCommand.self,
            AuthCommand.self,
            VersionCommand.self,
            WorkflowCommand.self,
            TUICommand.self,
            BundleIDsCommand.self,
            CertificatesCommand.self,
            DevicesCommand.self,
            ProfilesCommand.self,
            AppPreviewSetsCommand.self,
            AppPreviewsCommand.self,
            IAPCommand.self,
            IAPLocalizationsCommand.self,
            SubscriptionGroupsCommand.self,
            SubscriptionsCommand.self,
            SubscriptionLocalizationsCommand.self,
            SubscriptionOffersCommand.self,
            SubscriptionOfferCodesCommand.self,
            SubscriptionOfferCodeCustomCodesCommand.self,
            SubscriptionOfferCodeOneTimeCodesCommand.self,
            IAPOfferCodesCommand.self,
            IAPOfferCodeCustomCodesCommand.self,
            IAPOfferCodeOneTimeCodesCommand.self,
            AppShotsCommand.self,
            AgeRatingCommand.self,
            AppCategoriesCommand.self,
            VersionReviewDetailCommand.self,
            PluginsCommand.self,
            SkillsCommand.self,
            AppWallCommand.self,
            UsersCommand.self,
            UserInvitationsCommand.self,
            MetadataCommand.self,
            MigrateCommand.self,
            XcodeCommand.self,
            XcodeCloudCommand.self,
            GameCenterCommand.self,
            NotarizationCommand.self,
            SigningCommand.self,
            AppClipsCommand.self,
            AppClipExperiencesCommand.self,
            AppClipExperienceLocalizationsCommand.self,
            SalesReportsCommand.self,
            FinanceReportsCommand.self,
            AnalyticsReportsCommand.self,
            ReviewsCommand.self,
            ReviewResponsesCommand.self,
            PerfMetricsCommand.self,
            DiagnosticsCommand.self,
            DiagnosticLogsCommand.self,
            BetaReviewCommand.self,
            AppAvailabilityCommand.self,
            IAPAvailabilityCommand.self,
            SubscriptionAvailabilityCommand.self,
            TerritoriesCommand.self,
            WebCommand.self,
            WebServerCommand.self,
            IrisCommand.self,
            SimulatorsCommand.self,
        ] + plugins.flatMap { $0.plugin.commands.compactMap { $0 as? any ParsableCommand.Type } }
    )
}
